name: insights
on:
  workflow_dispatch:
jobs:
  unfollowers:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Build
        run: make build
      - name: Add build directory to path
        run: echo "${GITHUB_WORKSPACE}/build" >> $GITHUB_PATH
      - name: Load Instagram information
        run: instagram information load ${{ secrets.ARCHIVE_URL }}
      - name: Retrieve a list of users who are not following you back
        run: instagram followdata unfollowers
      - name: Cleanup local Instagram information
        run: instagram information cleanup
